namespace Quicker.Settings.Code;

public enum SettingPageId
{
	Invalid,
	BasicInfo,
	FunctionHotkeys,
	GeneralTriggerSettings,
	AutoRunActions,
	AppSettings,
	QuickCaptureSettings,
	FloatSettings,
	BlockOptions,
	PanelPopupSettings,
	PanelWindowSettingsPage,
	PanelTriggerKeySettings,
	PanelWindow,
	SearchSettings,
	BlackListSettings,
	UISettingsPage,
	ContextMenuGeneralSettings,
	TextContextMenuSettings,
	ImageContextMenuSettings,
	FileContextMenuSettings,
	BasicToolsSettingPage,
	ActionRecycleBinSettingPage,
	UpdateActionsPage,
	AboutSettingPage,
	// 保持既有页面编号，避免移除统计页后改变旧的页面引用。
	HelperFunctionsSettingPage = 25,
	SyncSettingPage,
	LeftButtonPlusSettingPage,
	CircleMenuSettingPage,
	GesturesSettingPage,
	ActionHotkeysSettingPage,
	PowerKeysSettingPage,
	PowerKeysManagementPage,
	PowerKeysSettingsPage,
	TextCommandManagePage,
	TextCommandSettingPage,
	MouseActionManagePage,
	ThanksPage,
	PrivacyPolicy,
	GesturesManagePage,
	CircleMenuManagePage,
	LeftButonPlusProfileSettings,
	ActionDesignerSettingsPage,
	BasicTriggers,
	KeyActionManagePage,
	EventTriggerSettingsPage,
	HotkeyWatcherSettingsPage
}
